name: Bump version

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  bump-version:
    if: "github.event.pull_request.merged == true && !startsWith(github.event.pull_request.title, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          fetch-depth: 0
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Configure Git
        run: |
          git config user.name "Ngezler"
          git config user.email "xhalanga2@gmail.com"
      - name: Push changes
        run: |
          git push origin master
          git push --tags
